/**
 * Design reminder — release-specific training replica: model only the observable V200R021C10SPC200
 * workflow and label all scenario data as non-live; do not present it as Huawei’s original software.
 */
import { useState } from "react";
import { Activity, AlertTriangle, BarChart3, BellRing, ChevronDown, ChevronRight, CircleAlert, FileDown, History, LayoutDashboard, Network, RadioTower, Search, ShieldAlert, SlidersHorizontal, Table2 } from "lucide-react";
import "./WebLctReplica.css";
import "./WebLctReplicaRefinements.css";

type Screen = "alarms" | "hop" | "performance";
type PerformanceMode = "current" | "history";
type HistoryView = "table" | "power" | "errors";

const observedMetrics = ["Power to be Received", "Actual Receive Power", "Transmit Power", "Actual Transmit Power", "ES", "SES", "CSES", "UAS", "BBE"];

export default function WebLctReplica() {
  const [screen, setScreen] = useState<Screen>("alarms");
  const [mode, setMode] = useState<PerformanceMode>("current");
  const [historyView, setHistoryView] = useState<HistoryView>("table");
  const [queried, setQueried] = useState(false);
  const [resolution, setResolution] = useState("15-Minute");
  const openPerformance = (target: PerformanceMode = "current") => { setScreen("performance"); setMode(target); setQueried(false); };
  return <main className="replica-page">
    <div className="replica-watermark">TRAINING REPLICA · NOT PRODUCTION SOFTWARE</div>
    <header className="replica-top"><div className="replica-title"><Network size={18} /><b>NE Explorer</b><span>V200R021C10SPC200 workflow training replica</span></div><div className="replica-actions"><button><Search size={14} /></button><button><BellRing size={14} /></button><button><ShieldAlert size={14} /></button></div></header>
    <div className="replica-subtop"><span className="replica-chip">TRAINING NE</span><span>NE Name: <b>MW-TRAIN-NE</b></span><span>NE State: <i /> RUNNING — simulated</span><span>Release reference: V200R021C10SPC200</span><span className="replica-legal">No Huawei session or device data</span></div>
    <section className="replica-shell">
      <aside className="replica-tree"><div className="device-caption">Training NE Explorer</div><div className="device-tree"><b><ChevronDown size={12} /> MW-TRAIN-NE</b><span><ChevronDown size={12} /> Shelf-0</span><span>1-ISMB</span><span>4-ODU</span><span>6-ISMB</span><span>Radio Links</span></div><div className="tree-caption">Function Tree</div><TreeNode icon={<SlidersHorizontal size={14} />} label="Configuration" /><TreeNode icon={<Activity size={14} />} label="Diagnosis & Maintenance" /><TreeNode icon={<CircleAlert size={14} />} label="Fault" active={screen === "alarms"} onClick={() => setScreen("alarms")} /><TreeNode icon={<History size={14} />} label="Performance" /><button onClick={() => setScreen("hop")} className={screen === "hop" || screen === "performance" ? "rep-tree-node active-parent" : "rep-tree-node"}><ChevronDown size={13} /><RadioTower size={14} /><b>Radio Links</b></button>{(screen === "hop" || screen === "performance") && <div className="rep-tree-child"><button onClick={() => setScreen("hop")} className={screen === "hop" ? "active" : ""}>HOP Management</button><button onClick={() => openPerformance("current")} className={screen === "performance" ? "active" : ""}>Microwave Link Performance</button></div>}<TreeNode icon={<FileDown size={14} />} label="Report" /><div className="tree-release"><b>Release scope</b><span>This replica covers the visible performance workflow only.</span></div></aside>
      <section className="replica-main">
        {screen === "alarms" && <AlarmScreen onOpenHop={() => setScreen("hop")} />}
        {screen === "hop" && <HopScreen onOpenPerformance={() => openPerformance("current")} onOpenAlarms={() => setScreen("alarms")} />}
        {screen === "performance" && <PerformanceScreen mode={mode} setMode={(value) => { setMode(value); setQueried(false); }} queried={queried} setQueried={setQueried} resolution={resolution} setResolution={setResolution} historyView={historyView} setHistoryView={setHistoryView} />}
      </section>
    </section>
    <footer className="replica-footer">Observed menu/tabs are modeled from the user-supplied performance video. All NEs, events, counters, charts, and states in this screen are training-only.</footer>
  </main>;
}

function TreeNode({ icon, label, active, onClick }: { icon: React.ReactNode; label: string; active?: boolean; onClick?: () => void }) { return <button onClick={onClick} className={active ? "rep-tree-node active" : "rep-tree-node"}>{icon}<span>{label}</span></button>; }

function AlarmScreen({ onOpenHop }: { onOpenHop: () => void }) { return <div className="rep-screen"><div className="rep-crumb">Fault <ChevronRight size={12} /> <b>Browse Alarms</b></div><div className="rep-heading"><div><p>NE EXPLORER / TRAINING VIEW</p><h1>Browse Current Alarms</h1><span>Training-only alarm list. It does not represent a live device or active incident.</span></div><button className="rep-primary" onClick={onOpenHop}>Open Radio Links <ChevronRight size={14} /></button></div><div className="rep-toolbar"><span>Severity: <b>All</b></span><span>Type: <b>Current</b></span><button><FileDown size={13} /> Save As</button><button><Search size={13} /> Query</button></div><table className="rep-table"><thead><tr><th>Severity</th><th>Alarm name</th><th>Object</th><th>Rising time</th><th>Type</th></tr></thead><tbody><tr><td><span className="severity training">Training</span></td><td>Scenario context only</td><td>MW-TRAIN-NE</td><td>—</td><td>Non-live</td></tr></tbody></table><section className="rep-detail"><h3>Alarm details / causes</h3><p>Select an item in a production NE Explorer to review details. This replica deliberately contains no live alarms or inferred fault causes.</p></section></div>; }

function HopScreen({ onOpenPerformance, onOpenAlarms }: { onOpenPerformance: () => void; onOpenAlarms: () => void }) { return <div className="rep-screen"><div className="rep-crumb">Radio Links <ChevronRight size={12} /> <b>HOP Management</b></div><div className="rep-heading"><div><p>NE EXPLORER / RADIO LINKS</p><h1>HOP Management</h1><span>Choose the performance tab to follow the monitored workflow from the reference video.</span></div><div className="rep-link-state"><RadioTower size={16} /><span>Training link topology</span><b>Not operational</b></div></div><div className="rep-tabs hop-tabs"><button>Slot Layout</button><button className="active">HOP Management</button><button onClick={onOpenPerformance}>Microwave Link Performance</button><button onClick={onOpenAlarms}>Browse Current Alarms</button><button>Browse History Alarms</button></div><div className="hop-workspace"><div className="hop-card"><span>Source NE</span><b>MW-TRAIN-A</b><small>Training endpoint</small></div><div className="hop-path"><i /><span>Microwave link · training topology</span><i /></div><div className="hop-card"><span>Sink NE</span><b>MW-TRAIN-B</b><small>Training endpoint</small></div></div><div className="rep-insight"><AlertTriangle size={16} /><p>Topology names and state are fictional training data. In the target system, confirm the actual HOP and both NE identities before querying or changing anything.</p></div></div>; }

function PerformanceScreen({ mode, setMode, queried, setQueried, resolution, setResolution, historyView, setHistoryView }: { mode: PerformanceMode; setMode: (value: PerformanceMode) => void; queried: boolean; setQueried: (value: boolean) => void; resolution: string; setResolution: (value: string) => void; historyView: HistoryView; setHistoryView: (value: HistoryView) => void }) { return <div className="rep-screen"><div className="rep-crumb">Radio Links <ChevronRight size={12} /> HOP Management <ChevronRight size={12} /> <b>Microwave Link Performance</b></div><div className="rep-heading"><div><p>V200R021C10SPC200 OBSERVED WORKFLOW</p><h1>Microwave Link Performance</h1><span>Current and history views follow the visible query sequence; their data is intentionally non-operational.</span></div></div><div className="rep-tabs observed-tabs"><button>Slot Layout</button><button>HOP Management</button><button className="selected-parent">Microwave Link Performance</button></div><div className="rep-tabs performance-tabs"><button className={mode === "current" ? "active" : ""} onClick={() => { setMode("current"); setQueried(false); }}>Current Performance</button><button className={mode === "history" ? "active" : ""} onClick={() => { setMode("history"); setQueried(false); }}>History Performance</button></div>{mode === "current" ? <CurrentControls queried={queried} setQueried={setQueried} /> : <HistoryControls queried={queried} setQueried={setQueried} resolution={resolution} setResolution={setResolution} historyView={historyView} setHistoryView={setHistoryView} />}</div>; }

function CurrentControls({ queried, setQueried }: { queried: boolean; setQueried: (value: boolean) => void }) { return <><div className="rep-controlbar"><label><input type="checkbox" /> Auto Refresh</label><span className="spacer" /><button><FileDown size={13} /> Save As...</button><button className="rep-query" onClick={() => setQueried(true)}><Search size={13} /> Query</button></div>{queried ? <CurrentTable /> : <QueryEmpty title="Current Performance" text="Use Query to display a training-only comparison of near-end and far-end performance categories." />}</>; }

function HistoryControls({ queried, setQueried, resolution, setResolution, historyView, setHistoryView }: { queried: boolean; setQueried: (value: boolean) => void; resolution: string; setResolution: (value: string) => void; historyView: HistoryView; setHistoryView: (value: HistoryView) => void }) { return <><div className="rep-history-controls"><div><b>Resolution</b><select value={resolution} onChange={(event) => setResolution(event.target.value)}><option>15-Minute</option><option>24 Hour</option></select></div><div><b>Period Time</b><span className="date-control">Training From <ChevronDown size={12} /></span><span className="date-control">Training To <ChevronDown size={12} /></span></div><div><b>Display Format</b><button className={historyView === "table" ? "format active" : "format"} onClick={() => setHistoryView("table")}><Table2 size={12} /> Table</button><button className={historyView !== "table" ? "format active" : "format"} onClick={() => setHistoryView("power")}><BarChart3 size={12} /> Chart</button></div><span className="spacer" /><button><FileDown size={13} /> Save As...</button><button className="rep-query" onClick={() => setQueried(true)}><Search size={13} /> Query</button></div>{queried ? historyView === "table" ? <HistoryTable resolution={resolution} /> : <HistoryChart historyView={historyView} setHistoryView={setHistoryView} /> : <QueryEmpty title="History Performance" text="Select Resolution, Period Time, and Display Format, then query the training-only history view." />}</>; }

function QueryEmpty({ title, text }: { title: string; text: string }) { return <div className="rep-query-empty"><Search size={25} /><div><b>{title} is ready</b><p>{text}</p></div></div>; }

function CurrentTable() { return <div className="rep-results"><div className="rep-result-caption"><span>✓</span> Training query complete · current performance categories only</div><table className="rep-table metric-table"><thead><tr><th>Performance event</th><th>Near-End / 15 Minute</th><th>Near-End / 24 Hour</th><th>Far-End / 15 Minute</th><th>Far-End / 24 Hour</th></tr></thead><tbody>{observedMetrics.map((metric) => <tr key={metric}><td>{metric}</td><td>Training placeholder</td><td>Training placeholder</td><td>Training placeholder</td><td>Training placeholder</td></tr>)}</tbody></table><p className="rep-data-note">Values are intentionally blank placeholders. Use the actual V200R021C10SPC200 environment and approved data source for genuine power, RSL, or error-counter readings.</p></div>; }

function HistoryTable({ resolution }: { resolution: string }) { return <div className="rep-results"><div className="rep-result-caption"><span>✓</span> Training history query · {resolution}</div><table className="rep-table"><thead><tr><th>Date</th><th>Source NE / RX power trend</th><th>Sink NE / RX power trend</th><th>ES / SES / CSES / UAS / BBE</th></tr></thead><tbody>{["Training interval A", "Training interval B", "Training interval C", "Training interval D"].map((date) => <tr key={date}><td>{date}</td><td>Non-live comparison placeholder</td><td>Non-live comparison placeholder</td><td>Not operational</td></tr>)}</tbody></table></div>; }

function HistoryChart({ historyView, setHistoryView }: { historyView: HistoryView; setHistoryView: (value: HistoryView) => void }) { const isErrors = historyView === "errors"; return <div className="rep-results rep-chart-results"><div className="rep-result-caption"><span>✓</span> Training chart query · no device values</div><div className="chart-toggle"><label><input type="radio" checked={!isErrors} onChange={() => setHistoryView("power")} /> Link TX/RX Power</label><label><input type="radio" checked={isErrors} onChange={() => setHistoryView("errors")} /> Link Errors</label><span>Legend</span></div><div className="rep-chart"><div className="rep-grid-lines"><i /><i /><i /><i /><i /></div>{isErrors ? <div className="chart-empty">No training points selected for the error-chart example.</div> : <svg viewBox="0 0 760 250" aria-label="Training-only power trend chart"><polyline points="16,174 100,128 180,155 264,93 352,120 447,72 540,101 638,58 745,82" fill="none" stroke="#2e86a0" strokeWidth="4" /><polyline points="16,147 100,165 180,111 264,134 352,86 447,109 540,65 638,92 745,47" fill="none" stroke="#c9783e" strokeWidth="4" strokeDasharray="9 7" /></svg>}</div><div className="rep-chart-legend"><span><i /> Source NE training trend</span><span><i /> Sink NE training trend</span></div></div>; }
